version: '3.7'
services:
  clusauth:
    build:
      context: ${CLUSAUTH_CONTEXT-..}
      dockerfile: ${CLUSAUTH_DOCKERFILE-./build/Dockerfile}
    image: clusauth
    container_name: clusauth
    ports:
      - ${CLUSAUTH_PORT-8003}:9090
    restart: always
    volumes:
      - ${CLUSAUTH_CONFIG-../config/}:/config/
      - ${CLUSAUTH_DATA-../data/}:/data/
